export const ERROR_CODES = {
    MISSING_ID_OR_PASSWORD: 'MISSING_ID_OR_PASSWORD', // ID 또는 비밀번호가 제공되지 않음
    INVALID_ID_FORMAT: 'INVALID_ID_FORMAT', // ID 형식이 유효하지 않음
    INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT', // 비밀번호 형식이 유효하지 않음
    USER_NOT_FOUND: 'USER_NOT_FOUND', // 사용자 찾을 수 없음
    INCORRECT_ID_OR_PASSWORD: 'INCORRECT_ID_OR_PASSWORD', // ID 또는 비밀번호가 틀림
    FORBIDDEN: 'FORBIDDEN', // 접근 권한 없음
    UNAUTHORIZED: 'UNAUTHORIZED', // 접근 권한 인증 필요
    TOKEN_EXPIRED: 'TOKEN_EXPIRED', // 인증 토큰 만료
    TOKEN_INVALID: 'TOKEN_INVALID', // 인증 토큰 유효하지 않음
    DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR', // 데이터베이스 연결 오류
    INTERNAL_SERVER: 'INTERNAL_SERVER', // 서버 오류
    UNKNOWN: 'UNKNOWN', // 알 수 없는 오류
}
