import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { RootProvider } from '@/lib/providers'
import { TopLoadingBar } from '@/features/top-loading-bar'
import { Suspense } from 'react'
import { Footer, Header } from '@/features/layout'
import '@/lib/css/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <RootProvider>
                    <Suspense fallback={null}>
                        <TopLoadingBar />
                    </Suspense>
                    <div className='flex w-full min-h-dvh flex-col items-center justify-center'>
                        <Header />
                        <div className='flex flex-col w-full flex-1 bg-orange-100'>{children}</div>
                        <Footer />
                    </div>
                </RootProvider>
            </body>
        </html>
    )
}
