import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/lib/css/globals.css'
import { RootProvider } from '@/lib/providers'
import { TopLoadingBar } from '@/features/top-loading-bar'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <RootProvider>
                    <Suspense fallback={null}>
                        <TopLoadingBar />
                    </Suspense>
                    {children}
                </RootProvider>
            </body>
        </html>
    )
}
