name: Dokcer Build and Deploy to Vercel

# main 브렌치에 푸시할 떄 워크플로우 실행
on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. 저장소에서 코드 클론
            - uses: actions/checkout@v2

            # 2. Docker 이미지 빌드
            - name: Build Docker Image
              run: docker build -t eunstory-app:latest .

              # 3. Vercel CLI 설치
            - name: Install Vercel CLI
              run: npm install -g vercel@latest

            # 4. Vercel 환경 정보 가져오기
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # 5. Docker 컨테이너를 기반으로 Vercel에서 빌드
            - name: Build Project Artifacts using Docker
              run: |
                  docker run -d -p 3000:3000 --name eunstory-app eunstory-app:latest
                  sleep 30  # 컨테이너가 시작되도록 대기

            # 6. Vercel에 배포
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

            # 7. Docker 컨테이너 종료 및 정리
            - name: Clean up Docker
              run: |
                  docker stop eunstory-app
                  docker rm eunstory-app
