name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
    push:
        branches:
            - main

jobs:
    deploy-production:
        runs-on: ubuntu-latest

        steps:
            # 1. GitHub 리포지토리에서 소스코드 체크아웃
            - uses: actions/checkout@v2

            # 2. Docker 이미지 빌드
            - name: Build Docker Image
              run: docker build -t eunstory-app:latest .

            # 3. Docker 이미지를 Vercel에 배포하기 위해 Vercel CLI 설치
            - name: Install Vercel CLI
              run: npm install --global vercel@canary

            # 4. Vercel 환경 설정 정보 가져오기
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # 5. Docker 이미지를 Vercel로 배포
            - name: Deploy Docker Image to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
