name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest

        steps:
            # 1. GitHub 저장소에서 소스 코드를 체크아웃합니다.
            - name: Checkout Repository
              uses: actions/checkout@v2

            # 2. Docker 이미지를 빌드합니다.
            - name: Build Docker Image
              run: docker build -t eunstory-app:latest .

            # 3. Docker 이미지를 Vercel에 배포합니다.
            - name: Deploy to Vercel
              env:
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |
                  vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

            # 4. (Optional) Docker 이미지 클린업
            - name: Cleanup Docker Images
              run: docker rmi eunstory-app:latest
