name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

on:
    push:
        branches:
            - main

jobs:
    deploy-production:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # Docker 이미지 빌드
            - name: Build Docker Image
              working-directory: ./ # 루트 디렉토리에서 실행되도록 설정
              run: |
                  docker build \
                    --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
                    --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
                    --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
                    -t eunstory:latest .

            # Vercel CLI 설치
            - name: Install Vercel CLI
              run: npm install --global vercel

            # Vercel에 Docker 이미지 배포
            - name: Deploy to Vercel
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
