name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            # 1. 저장소 체크아웃
            - uses: actions/checkout@v2

            # 2. pnpm 설치
            - name: Install pnpm
              run: npm install -g pnpm

            # 3. pnpm global 설정
            - name: Setup pnpm global bin directory
              run: pnpm setup

            # 4. 프로젝트 의존성 설치
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # 5. Vercel CLI 설치
            - name: Install Vercel CLI
              run: pnpm add -g vercel@latest

            # 6. Vercel 환경 정보 가져오기
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # 7. 프로젝트 빌드
            - name: Build Project Artifacts
              run: pnpm build

            # 8. Vercel에 프로젝트 배포
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
