name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - main

jobs:
    deploy-production:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: npm install --global pnpm

            - name: Install Vercel CLI
              run: npm install --global vercel@canary

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
