name: GitHub Actions Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
    push:
        branches:
            - main

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest

        steps:
            # 1. 저장소에서 코드 클론
            - uses: actions/checkout@v2

            # 2. pnpm 설치
            - name: Install pnpm
              run: npm install --global pnpm

            # 3. Vercel CLI 설치
            - name: Install Vercel CLI
              run: npm install --global vercel@canary

            # 4. Vercel 프로젝트 설정 정보 가져오기
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            # 5. 의존성 설치
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # 6. Prisma 마이그레이션 적용 (배포 전 데이터베이스 스키마 적용)
            - name: Run Prisma Migrations
              run: pnpm prisma migrate deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }} # 명시적으로 환경 변수를 설정

            # 7. 빌드 실행
            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            # 8. 배포 실행
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
